// Traces the wordmark, `co.` and rule out of plexo-logo.svg into a typed data
// module the Logo component renders. Coordinates stay in the file's canvas
// space (1500 × 1500); the wrapper offset (273, 52) is folded into the
// wordmark glyph transforms so everything shares one coordinate system.
import { readFileSync, writeFileSync } from "node:fs";

const [, , inPath, outPath] = process.argv;
const svg = readFileSync(inPath, "utf8").replace(/\n/g, "");

const groups = [];
const re = /<g transform="translate\(([-\d.]+), ([-\d.]+)\)"><g><path d="([^"]+)"\/><\/g><\/g>/g;
let m;
while ((m = re.exec(svg))) {
  groups.push({ tx: +m[1], ty: +m[2], d: m[3].trim() });
}

// Wordmark: the five glyph groups on baseline 845.717834 inside the (273, 52) wrapper.
const word = groups
  .filter((g) => Math.abs(g.ty - 845.717834) < 0.01)
  .map((g) => ({ tx: +(g.tx + 273).toFixed(6), ty: +(g.ty + 52).toFixed(6), d: g.d }));
if (word.length !== 5) throw new Error(`expected 5 wordmark glyphs, got ${word.length}`);

// `co.`: the three groups right-aligned at x = 1274.830244, at canvas level.
const co = groups.filter((g) => Math.abs(g.tx - 1274.830244) < 0.01);
if (co.length !== 3) throw new Error(`expected 3 co. glyphs, got ${co.length}`);

// The rule: a stroked path at matrix(0.75, 0, 0, 0.75, 222.019965, 895.363199),
// baked into canvas coordinates so it can be drawn with pathLength.
const S = 0.75, TX = 222.019965, TY = 895.363199;
const p = (x, y) => `${(x * S + TX).toFixed(3)} ${(y * S + TY).toFixed(3)}`;
const rule =
  `M ${p(-0.000578902, 99.890743)} L ${p(1139.374519, 99.890743)} ` +
  `C ${p(1154.285979, 99.890743)} ${p(1166.374522, 87.802201)} ${p(1166.374522, 72.890741)} ` +
  `L ${p(1166.374522, 0.000109828)}`;
const strokeWidth = +(33 * S).toFixed(3);
const ruleY = +(99.890743 * S + TY).toFixed(3);

const glyphNames = ["p", "l", "e", "x", "o"];
const out = `// GENERATED by scripts/trace-logo.mjs from plexo-logo.svg. Do not edit by hand.
// All coordinates are in the original file's 1500 × 1500 canvas space.

export type Glyph = { name: string; tx: number; ty: number; d: string };

/** The five wordmark glyphs, wrapper offset folded in. */
export const WORDMARK: Glyph[] = ${JSON.stringify(
  word.map((g, i) => ({ name: glyphNames[i], ...g })),
  null,
  2
)};

/** \`co.\`, rotated 90° CCW, right-aligned at x = 1274.83. Order: c, o, period. */
export const CO: Glyph[] = ${JSON.stringify(
  co.map((g, i) => ({ name: ["c", "o", "period"][i], ...g })),
  null,
  2
)};

/** The baseline rule: enters from the left, runs under the word, turns up into the o. Stroked, not filled. */
export const RULE = {
  d: ${JSON.stringify(rule)},
  strokeWidth: ${strokeWidth},
  /** y of the rule's centreline */
  y: ${ruleY},
  /** x where the rule begins */
  x0: ${TX},
} as const;

/** Tight boxes for the two lockups (see DESIGN.md §0). */
export const BOXES = {
  /** wordmark + rule + co. */
  lockup: { x: 222, y: 342, w: 1054, h: 716 },
  /** the p and the fragment of rule that crosses it */
  monogram: { x: 222, y: 500, w: 290, h: 558 },
} as const;
`;
writeFileSync(outPath, out);
console.log(`wrote ${outPath}: ${word.length} wordmark glyphs, ${co.length} co. glyphs, rule y=${ruleY}, stroke=${strokeWidth}`);
